namespace WinUINotes.Models
{
    [default_interface]
    runtimeclass Note 
    {
        Note();
        String FileName;
        String Text;
        Windows.Foundation.DateTime Date;

        Windows.Foundation.IAsyncAction SaveAsync();
        Windows.Foundation.IAsyncAction DeleteAsync();
    }
}
