namespace WinUINotes.Models
{
    [default_interface]
    runtimeclass NoteModel 
    {
        NoteModel();
        String FileName;
        String Text;
        Windows.Foundation.DateTime Date;
        String DateText { get; };

        Windows.Foundation.IAsyncAction SaveAsync();
        Windows.Foundation.IAsyncAction DeleteAsync();
    }
}
