namespace WinUINotes.Models
{
    [default_interface]
    runtimeclass NoteModel 
    {
        NoteModel();
        String FileName;
        String Title;
        String Text;
        Windows.Foundation.DateTime Date;
        String DateText { get; };
    }
}
