import "Models/AllNotesModel.idl";

namespace WinUINotes.Views
{
    [default_interface]
    runtimeclass AllNotesPage : Microsoft.UI.Xaml.Controls.Page
    {
        AllNotesPage();
        WinUINotes.Models.AllNotesModel AllNotes;
    }
}
