import "Models/Note.idl";

namespace WinUINotes.Views
{
    [default_interface]
    runtimeclass NotePage : Microsoft.UI.Xaml.Controls.Page
    {
        WinUINotes.Models.Note noteModel;
        NotePage();
    }
}